In [239]:
!pip install transformers
!pip install ipywidgets
!pip install IProgress
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


In [240]:
import transformers
import torch

In [241]:
from transformers import BertTokenizer, BertForMaskedLM

In [242]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')

loading file https://huggingface.co/bert-base-uncased/resolve/main/vocab.txt from cache at /root/.cache/huggingface/transformers/45c3f7a79a80e1cf0a489e5c62b43f173c15db47864303a55d623bb3c96f72a5.d789d64ebfe299b0e416afc4a169632f903f693095b4629a7ea271d5a0cf2c99
loading file https://huggingface.co/bert-base-uncased/resolve/main/added_tokens.json from cache at None
loading file https://huggingface.co/bert-base-uncased/resolve/main/special_tokens_map.json from cache at None
loading file https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json from cache at /root/.cache/huggingface/transformers/c1d7f0a763fb63861cc08553866f1fc3e5a6f4f07621be277452d26d71303b7e.20430bd8e10ef77a7d2977accefe796051e01bc2fc4aa146bc862997a1a15e79
loading configuration file https://huggingface.co/bert-base-uncased/resolve/main/config.json from cache at /root/.cache/huggingface/transformers/3c61d016573b14f7f008c02c4e51a366c67ab274726fe2910691e2a761acf43e.37395cee442ab11005bcd270f3c34464dc1704b715b5d7

In [243]:
text = ("Component: Topic: Should students be taught to compete or to cooperate?, Sentence: From this point of view, I firmly believe that we should attach more importance to cooperation during primary education., First or last in essay: Yes, First in paragraph: Yes, Last in paragraph: Yes, In in introduction: Yes, Is in conclusion: No. Part Of Speech tags: PRON, VERB, VERB, ADJ, NOUN, ADP, NOUN, ADP, ADJ, NOUN. Is this component a premise, a claim or a major claim? This component is a Claim.")

In [244]:
inputs = tokenizer(text, return_tensors='pt')

In [245]:
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [246]:
inputs

{'input_ids': tensor([[  101,  6922,  1024,  8476,  1024,  2323,  2493,  2022,  4036,  2000,
          5566,  2030,  2000, 17654,  1029,  1010,  6251,  1024,  2013,  2023,
          2391,  1997,  3193,  1010,  1045,  7933,  2903,  2008,  2057,  2323,
         22476,  2062,  5197,  2000,  6792,  2076,  3078,  2495,  1012,  1010,
          2034,  2030,  2197,  1999,  9491,  1024,  2748,  1010,  2034,  1999,
         20423,  1024,  2748,  1010,  2197,  1999, 20423,  1024,  2748,  1010,
          1999,  1999,  4955,  1024,  2748,  1010,  2003,  1999,  7091,  1024,
          2053,  1012,  2112,  1997,  4613, 22073,  1024,  4013,  2078,  1010,
         12034,  1010, 12034,  1010,  4748,  3501,  1010, 15156,  1010,  4748,
          2361,  1010, 15156,  1010,  4748,  2361,  1010,  4748,  3501,  1010,
         15156,  1012,  2003,  2023,  6922,  1037, 18458,  1010,  1037,  4366,
          2030,  1037,  2350,  4366,  1029,  2023,  6922,  2003,  1037,  4366,
          1012,   102]]), 'token_type_

In [247]:
tokenizer.decode(4366)

'c l a i m'

In [248]:
tokenizer.decode(inputs['input_ids'][0][119])

'c l a i m'

In [249]:
inputs['input_ids'].shape

torch.Size([1, 122])

In [250]:
#inputs['labels'] = inputs.input_ids.detach().clone()

In [251]:
#inputs['labels']

In [252]:
#inputs['labels'].shape

In [253]:
#inputs['labels'][0][0]

In [254]:
#import random

In [255]:
#ids_randomlist = random.sample(range(0, 30522), 62)

In [256]:
#ids_randomlist

In [257]:
#len(ids_randomlist)

In [258]:
#repetitive_list = [2044] * 62

In [259]:
#repetitive_list

In [260]:
#len(repetitive_list)

In [261]:
#labels_custom = torch.tensor([[5367, 1996, 4883]])

In [262]:
#labels_custom.shape

In [263]:
#labels_custom[0][0]

In [264]:
# all things seem correct now

In [265]:
# give a set of custom/limited labels, see if it works
#inputs['labels'] = torch.tensor([ids_randomlist])

In [266]:
#inputs['labels'] = torch.tensor([repetitive_list])

# optional

In [267]:
# create random array of floats in equal dimension to input_ids
# rand = torch.rand(inputs.input_ids.shape)
# # where the random array is less than 0.15, we set true
# mask_arr = rand < 0.15
# mask_arr

In [268]:
#(inputs.input_ids != 101) * (inputs.input_ids != 102)

In [269]:
# mask_arr = (rand < 0.15) * (inputs.input_ids != 101) * (inputs.input_ids != 102)
# mask_arr

In [270]:
# create selection from mask_arr
# selection = torch.flatten((mask_arr[0]).nonzero()).tolist()
# selection

In [271]:
# apply selection index to inputs.input_ids, adding MASK tokens
inputs.input_ids[0][119] = 103

In [272]:
inputs

{'input_ids': tensor([[  101,  6922,  1024,  8476,  1024,  2323,  2493,  2022,  4036,  2000,
          5566,  2030,  2000, 17654,  1029,  1010,  6251,  1024,  2013,  2023,
          2391,  1997,  3193,  1010,  1045,  7933,  2903,  2008,  2057,  2323,
         22476,  2062,  5197,  2000,  6792,  2076,  3078,  2495,  1012,  1010,
          2034,  2030,  2197,  1999,  9491,  1024,  2748,  1010,  2034,  1999,
         20423,  1024,  2748,  1010,  2197,  1999, 20423,  1024,  2748,  1010,
          1999,  1999,  4955,  1024,  2748,  1010,  2003,  1999,  7091,  1024,
          2053,  1012,  2112,  1997,  4613, 22073,  1024,  4013,  2078,  1010,
         12034,  1010, 12034,  1010,  4748,  3501,  1010, 15156,  1010,  4748,
          2361,  1010, 15156,  1010,  4748,  2361,  1010,  4748,  3501,  1010,
         15156,  1012,  2003,  2023,  6922,  1037, 18458,  1010,  1037,  4366,
          2030,  1037,  2350,  4366,  1029,  2023,  6922,  2003,  1037,   103,
          1012,   102]]), 'token_type_

In [273]:
inputs['input_ids'][0][:]

tensor([  101,  6922,  1024,  8476,  1024,  2323,  2493,  2022,  4036,  2000,
         5566,  2030,  2000, 17654,  1029,  1010,  6251,  1024,  2013,  2023,
         2391,  1997,  3193,  1010,  1045,  7933,  2903,  2008,  2057,  2323,
        22476,  2062,  5197,  2000,  6792,  2076,  3078,  2495,  1012,  1010,
         2034,  2030,  2197,  1999,  9491,  1024,  2748,  1010,  2034,  1999,
        20423,  1024,  2748,  1010,  2197,  1999, 20423,  1024,  2748,  1010,
         1999,  1999,  4955,  1024,  2748,  1010,  2003,  1999,  7091,  1024,
         2053,  1012,  2112,  1997,  4613, 22073,  1024,  4013,  2078,  1010,
        12034,  1010, 12034,  1010,  4748,  3501,  1010, 15156,  1010,  4748,
         2361,  1010, 15156,  1010,  4748,  2361,  1010,  4748,  3501,  1010,
        15156,  1012,  2003,  2023,  6922,  1037, 18458,  1010,  1037,  4366,
         2030,  1037,  2350,  4366,  1029,  2023,  6922,  2003,  1037,   103,
         1012,   102])

In [274]:
tokenizer.decode(2044)

'a f t e r'

In [275]:
tokenizer.decode(inputs['input_ids'][0][:])    #decode(inputs['input_ids'])

'[CLS] component : topic : should students be taught to compete or to cooperate?, sentence : from this point of view, i firmly believe that we should attach more importance to cooperation during primary education., first or last in essay : yes, first in paragraph : yes, last in paragraph : yes, in in introduction : yes, is in conclusion : no. part of speech tags : pron, verb, verb, adj, noun, adp, noun, adp, adj, noun. is this component a premise, a claim or a major claim? this component is a [MASK]. [SEP]'

In [276]:
inputs

{'input_ids': tensor([[  101,  6922,  1024,  8476,  1024,  2323,  2493,  2022,  4036,  2000,
          5566,  2030,  2000, 17654,  1029,  1010,  6251,  1024,  2013,  2023,
          2391,  1997,  3193,  1010,  1045,  7933,  2903,  2008,  2057,  2323,
         22476,  2062,  5197,  2000,  6792,  2076,  3078,  2495,  1012,  1010,
          2034,  2030,  2197,  1999,  9491,  1024,  2748,  1010,  2034,  1999,
         20423,  1024,  2748,  1010,  2197,  1999, 20423,  1024,  2748,  1010,
          1999,  1999,  4955,  1024,  2748,  1010,  2003,  1999,  7091,  1024,
          2053,  1012,  2112,  1997,  4613, 22073,  1024,  4013,  2078,  1010,
         12034,  1010, 12034,  1010,  4748,  3501,  1010, 15156,  1010,  4748,
          2361,  1010, 15156,  1010,  4748,  2361,  1010,  4748,  3501,  1010,
         15156,  1012,  2003,  2023,  6922,  1037, 18458,  1010,  1037,  4366,
          2030,  1037,  2350,  4366,  1029,  2023,  6922,  2003,  1037,   103,
          1012,   102]]), 'token_type_

In [277]:
# pass inputs as kwarg to model
outputs = model(**inputs)

In [278]:
# we get two output tensors, loss and logits
outputs.keys()

odict_keys(['logits'])

In [279]:
outputs.logits.shape

torch.Size([1, 122, 30522])

In [280]:
desired_logits = outputs.logits[0][119]

In [281]:
desired_logits.shape

torch.Size([30522])

In [282]:
# get the index from the vocab

In [283]:
#full_dict = {v:k for k,v in tokenizer.get_vocab().items()}

In [284]:
#full_dict

In [285]:
#claim_idx = {v for k,v in tokenizer.get_vocab().items() if k == 'claim'}

In [286]:
#claim_idx

In [287]:
#prem_idx = {v for k,v in tokenizer.get_vocab().items() if k == 'premise'}

In [288]:
#prem_idx

In [289]:
desired_logits

tensor([-2.7223, -2.7466, -2.7926,  ..., -1.8121, -2.5870, -5.4545],
       grad_fn=<SelectBackward0>)

In [290]:
#desired_logits[0]

In [291]:
#desired_logits.shape

In [292]:
#desired_logits[0]

In [293]:
#logit_cl = desired_logits[0][4366]

In [294]:
#logit_cl

In [295]:
#logit_prem = desired_logits[0][18458]

In [296]:
#logit_prem

In [297]:
#torch.tensor([logit_cl,logit_prem])

In [298]:
#testing = torch.argmax(torch.tensor([logit_prem,logit_cl]))

In [299]:
#testing

In [300]:
### inference businsess

In [301]:
testing = torch.argmax(desired_logits)

In [302]:
testing

tensor(18458)

In [303]:
#full_dict = {v:k for k,v in tokenizer.get_vocab().items()}

In [304]:
#full_dict[2670]

In [305]:
tokenizer.decode(18458)

'p r e m i s e'

In [306]:
tokenizer.decode(4366)

'c l a i m'

In [307]:
tokenizer.decode(testing)

'p r e m i s e'

In [308]:
# ok good. now try to do this thing for a batch.

In [309]:
# so it can be any random idsm but has to be one of equal lenght.

In [310]:
# these are our predictions

In [311]:
# trainer.train()

In [312]:
# we get the answers for all masks
# then, we do the decod

## with 10 argument components

In [313]:
# get 10 texts from df

In [314]:
import pandas as pd

In [315]:
df = pd.read_pickle("/notebooks/Prompting/dataset/pe_dataset_w_prompts_1_pickle")

In [316]:
df

essay_nr component_id   label_and_comp_idxs  \
0     essay001           T1    MajorClaim 503 575   
1     essay001           T2  MajorClaim 2154 2231   
2     essay001           T3         Claim 591 714   
3     essay001           T4       Premise 716 851   
4     essay001           T5      Premise 853 1086   
...        ...          ...                   ...   
5968  essay402          T11     Premise 1275 1339   
5969  essay402          T12     Premise 1341 1388   
5970  essay402          T13     Premise 1393 1436   
5971  essay402          T14     Premise 1448 1525   
5972  essay402          T15         Claim 916 965   

                                                   text     label_x  \
0     we should attach more importance to cooperatio...  MajorClaim   
1     a more cooperative attitudes towards life is m...  MajorClaim   
2     through cooperation, children can learn about ...       Claim   
3     What we acquired from team work is not only ho...     Premise   
4     During the process of cooperation, children ca...     Premise   
...                                                 ...         ...   
5968  indirectly they will learn how to socialize ea...     Premise   
5969    That will make children getting lots of friends     Premise   
5970        they can contribute positively to community     Premise   
5971  playing sport makes children getting healthy a...     Premise   
5972  playing sports will give good effects on children       Claim   

     label_ComponentType relation_SupportAttack label_RelationType  \
0             MajorClaim                     []                      
1             MajorClaim                     []                      
2                  Claim                     []            Support   
3                Premise                     []            Support   
4                Premise                     []            Support   
...                  ...                    ...                ...   
5968             Premise                     []            Support   
5969             Premise                     []            Support   
5970             Premise                     []            Support   
5971             Premise                     []            Support   
5972               Claim                     []            Support   

     label_LinkedNotLinked  split  ... nr_preceeding_comps_in_para  \
0                   Linked  TRAIN  ...                           0   
1                   Linked  TRAIN  ...                           0   
2                   Linked  TRAIN  ...                           0   
3                NotLinked  TRAIN  ...                           1   
4                NotLinked  TRAIN  ...                           2   
...                    ...    ...  ...                         ...   
5968             NotLinked  TRAIN  ...                           4   
5969             NotLinked  TRAIN  ...                           5   
5970                Linked  TRAIN  ...                           6   
5971             NotLinked  TRAIN  ...                           7   
5972                Linked  TRAIN  ...                           0   

      nr_following_comps_in_para  \
0                              0   
1                              0   
2                              3   
3                              2   
4                              1   
...                          ...   
5968                           3   
5969                           2   
5970                           1   
5971                           0   
5972                           7   

                                 structural_fts_as_text  \
0     Topic: Should students be taught to compete or...   
1     Topic: Should students be taught to compete or...   
2     Topic: Should students be taught to compete or...   
3     Topic: Should students be taught to compete or...   
4     Topic: Should students be taught to compete or...   
...                                            

In [317]:
df['prompted_representation_1'][0:10]

0    Component: Topic: Should students be taught to...
1    Component: Topic: Should students be taught to...
2    Component: Topic: Should students be taught to...
3    Component: Topic: Should students be taught to...
4    Component: Topic: Should students be taught to...
5    Component: Topic: Should students be taught to...
6    Component: Topic: Should students be taught to...
7    Component: Topic: Should students be taught to...
8    Component: Topic: Should students be taught to...
9    Component: Topic: Should students be taught to...
Name: prompted_representation_1, dtype: object

In [318]:
texts_list = df['prompted_representation_1'][2:10].tolist()

In [319]:
texts_list

['Component: Topic: Should students be taught to compete or to cooperate?, Sentence: First of all, through cooperation, children can learn about interpersonal skills which are significant in the future life of all students, First or last in essay: No, First in paragraph: Yes, Last in paragraph: No, In in introduction: No, Is in conclusion: No. Part Of Speech tags: ADP, NOUN, PUNCT, NOUN, VERB, VERB, ADP, ADJ, NOUN, DET, AUX, ADJ, ADP, DET, ADJ, NOUN, ADP, DET, NOUN. Is this component a premise, a claim or a major claim? This component is a Claim.',
 'Component: Topic: Should students be taught to compete or to cooperate?, Sentence: What we acquired from team work is not only how to achieve the same goal with others but more importantly, how to get along with others, First or last in essay: No, First in paragraph: No, Last in paragraph: No, In in introduction: No, Is in conclusion: No. Part Of Speech tags: PRON, PRON, VERB, ADP, NOUN, NOUN, AUX, PART, ADV, ADV, PART, VERB, DET, ADJ, NOU

In [320]:
inputs_pe = tokenizer(texts_list, return_tensors='pt', max_length=512, truncation=True, padding='max_length')

In [321]:
inputs_pe

{'input_ids': tensor([[ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        ...,
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [322]:
inputs_pe['input_ids'].shape

torch.Size([8, 512])

In [323]:
# for training we will need labels

In [324]:
inputs_pe['labels'] = inputs_pe.input_ids.detach().clone()

In [325]:
inputs_pe

{'input_ids': tensor([[ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        ...,
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([[ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        ...,
      

In [326]:
# find where the last 102 is

In [327]:
(inputs_pe['input_ids'][0] == 102).nonzero(as_tuple=True)[0].item()

145

In [328]:
# claim = 4366, premise = 18458

In [329]:
(inputs_pe['input_ids'][1] == 102).nonzero(as_tuple=True)[0].item()

171

In [330]:
inputs_pe['input_ids'][1][169]

tensor(18458)

In [331]:
# confirm that all at len-2 indices are either claim or premise

In [332]:
last_indices_list = []

for i in range(8):
    last_idx = (inputs_pe['input_ids'][i] == 102).nonzero(as_tuple=True)[0].item()
    last_indices_list.append(last_idx)

In [333]:
last_indices_list

[145, 171, 220, 150, 101, 130, 152, 288]

In [334]:
last_indices_list = [x - 2 for x in last_indices_list]

In [335]:
last_indices_list

[143, 169, 218, 148, 99, 128, 150, 286]

In [336]:
# inputs_pe['input_ids'][0][143].item() # correct

In [337]:
last_indices_list

[143, 169, 218, 148, 99, 128, 150, 286]

In [338]:
inputs_pe['input_ids'][6][150].item()

18458

In [339]:
# now get a list of input ids at all these indics: they should be either claim = 4366, premise = 18458

In [340]:
list_index_minus_2 = []

for idx, val in enumerate(last_indices_list):
    print(idx,val)
    at_idx_minus_2 = inputs_pe['input_ids'][idx][val].item()
    list_index_minus_2.append(at_idx_minus_2)

0 143
1 169
2 218
3 148
4 99
5 128
6 150
7 286


In [341]:
list_index_minus_2

[4366, 18458, 18458, 18458, 4366, 18458, 18458, 18458]

In [342]:
# correct

In [343]:
# now make the above indices 103

In [344]:
for idx, val in enumerate(last_indices_list):
    inputs_pe['input_ids'][idx][val] = 103

In [345]:
# now check if they are 103

In [346]:
unsontroi_check_list = []

for idx, val in enumerate(last_indices_list):
    print(idx,val)
    at_idx_minus_2 = inputs_pe['input_ids'][idx][val].item()
    unsontroi_check_list.append(at_idx_minus_2)

0 143
1 169
2 218
3 148
4 99
5 128
6 150
7 286


In [347]:
unsontroi_check_list

[103, 103, 103, 103, 103, 103, 103, 103]

In [348]:
# correct

In [349]:
class PeMiniDataset(torch.utils.data.Dataset):
    def __init__(self, encodings):
        self.encodings = encodings
    def __getitem__(self, idx):
        return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
    def __len__(self):
        return len(self.encodings.input_ids)

In [350]:
dataset = PeMiniDataset(inputs_pe)

In [351]:
loader = torch.utils.data.DataLoader(dataset, batch_size=16, shuffle=True)

In [352]:
from transformers import TrainingArguments

args = TrainingArguments(
    output_dir='out',
    per_device_train_batch_size=16,
    num_train_epochs=2
)

PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).


In [353]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=dataset
)

In [354]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [355]:
model.to(device)

BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=Tr

In [356]:
trainer.train()

/opt/conda/lib/python3.8/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
***** Running training *****
  Num examples = 8
  Num Epochs = 2
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 2
/tmp/ipykernel_158/3831771474.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}




Training completed. Do not forget to share your model on huggingface.co/models =)




TrainOutput(global_step=2, training_loss=10.344411849975586, metrics={'train_runtime': 1.0493, 'train_samples_per_second': 15.249, 'train_steps_per_second': 1.906, 'total_flos': 4211277004800.0, 'train_loss': 10.344411849975586, 'epoch': 2.0})

In [357]:
model.eval()

BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=Tr

### now create a test set

In [362]:
df['prompted_representation_1'][11:19]

11    Component: Topic: More people are migrating to...
12    Component: Topic: More people are migrating to...
13    Component: Topic: More people are migrating to...
14    Component: Topic: More people are migrating to...
15    Component: Topic: More people are migrating to...
16    Component: Topic: More people are migrating to...
17    Component: Topic: More people are migrating to...
18    Component: Topic: More people are migrating to...
Name: prompted_representation_1, dtype: object

In [371]:
texts_list_test = df['prompted_representation_1'][13:22].tolist()

In [372]:
texts_list_test

['Component: Topic: More people are migrating to other countries than ever before, Sentence: Firstly, maintaining one’s cultural identity is a key important rule to help individuals emerge in the new multicultural environments, First or last in essay: No, First in paragraph: Yes, Last in paragraph: No, In in introduction: No, Is in conclusion: No. Part Of Speech tags: VERB, NUM, NUM, ADJ, NOUN, AUX, DET, ADJ, ADJ, NOUN, PART, VERB, NOUN, VERB, ADP, DET, ADJ, ADJ, NOUN. Is this component a premise, a claim or a major claim? This component is a Premise.',
 'Component: Topic: More people are migrating to other countries than ever before, Sentence: Thus this makes it clear that sustaining the cultural values of immigrants is paramount essential., First or last in essay: No, First in paragraph: No, Last in paragraph: Yes, In in introduction: No, Is in conclusion: No. Part Of Speech tags: VERB, DET, ADJ, NOUN, ADP, NOUN, AUX, ADJ, ADJ. Is this component a premise, a claim or a major claim? T

In [373]:
inputs_pe_test = tokenizer(texts_list_test, return_tensors='pt', max_length=512, truncation=True, padding='max_length')

In [374]:
inputs_pe_test

{'input_ids': tensor([[ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        ...,
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [375]:
inputs_pe_test['input_ids'].shape

torch.Size([9, 512])

In [323]:
# for training we will need labels

In [ ]:
# for testing we dont?

In [324]:
#inputs_pe['labels'] = inputs_pe.input_ids.detach().clone()

In [325]:
#inputs_pe

{'input_ids': tensor([[ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        ...,
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([[ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        [ 101, 6922, 1024,  ...,    0,    0,    0],
        ...,
      

In [326]:
# find where the last 102 is

In [376]:
(inputs_pe_test['input_ids'][0] == 102).nonzero(as_tuple=True)[0].item()

143

In [377]:
# claim = 4366, premise = 18458

In [378]:
(inputs_pe_test['input_ids'][1] == 102).nonzero(as_tuple=True)[0].item()

113

In [331]:
# confirm that all at len-2 indices are either claim or premise

In [380]:
last_indices_list = []

for i in range(9):
    last_idx = (inputs_pe_test['input_ids'][i] == 102).nonzero(as_tuple=True)[0].item()
    last_indices_list.append(last_idx)

In [381]:
last_indices_list

[143, 113, 188, 139, 149, 124, 149, 119, 129]

In [382]:
last_indices_list = [x - 2 for x in last_indices_list]

In [383]:
last_indices_list

[141, 111, 186, 137, 147, 122, 147, 117, 127]

In [384]:
# inputs_pe['input_ids'][0][143].item() # correct

In [385]:
last_indices_list

[141, 111, 186, 137, 147, 122, 147, 117, 127]

In [386]:
inputs_pe_test['input_ids'][6][147].item()

18458

In [339]:
# now get a list of input ids at all these indics: they should be either claim = 4366, premise = 18458

In [388]:
list_index_minus_2 = []

for idx, val in enumerate(last_indices_list):
    print(idx,val)
    at_idx_minus_2 = inputs_pe_test['input_ids'][idx][val].item()
    list_index_minus_2.append(at_idx_minus_2)

0 141
1 111
2 186
3 137
4 147
5 122
6 147
7 117
8 127


In [389]:
list_index_minus_2

[18458, 4366, 18458, 18458, 18458, 18458, 18458, 4366, 18458]

In [390]:
# correct

In [343]:
# now make the above indices 103

In [391]:
for idx, val in enumerate(last_indices_list):
    inputs_pe_test['input_ids'][idx][val] = 103

In [392]:
# now check if they are 103

In [394]:
unsontroi_check_list = []

for idx, val in enumerate(last_indices_list):
    print(idx,val)
    at_idx_minus_2 = inputs_pe_test['input_ids'][idx][val].item()
    unsontroi_check_list.append(at_idx_minus_2)

0 141
1 111
2 186
3 137
4 147
5 122
6 147
7 117
8 127


In [395]:
unsontroi_check_list

[103, 103, 103, 103, 103, 103, 103, 103, 103]

In [396]:
# correct

In [397]:
dataset_test = PeMiniDataset(inputs_pe_test)

In [410]:
test_loader = torch.utils.data.DataLoader(dataset_test, batch_size=16, shuffle=True)

In [411]:
dataset_test[0]['input_ids'], dataset_test[0]['attention_mask']

/tmp/ipykernel_158/3831771474.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}


(tensor([  101,  6922,  1024,  8476,  1024,  2062,  2111,  2024, 28636,  2000,
          2060,  3032,  2084,  2412,  2077,  1010,  6251,  1024, 15847,  1010,
          8498,  2028,  1521,  1055,  3451,  4767,  2003,  1037,  3145,  2590,
          3627,  2000,  2393,  3633, 12636,  1999,  1996,  2047, 27135, 10058,
          1010,  2034,  2030,  2197,  1999,  9491,  1024,  2053,  1010,  2034,
          1999, 20423,  1024,  2748,  1010,  2197,  1999, 20423,  1024,  2053,
          1010,  1999,  1999,  4955,  1024,  2053,  1010,  2003,  1999,  7091,
          1024,  2053,  1012,  2112,  1997,  4613, 22073,  1024, 12034,  1010,
         16371,  2213,  1010, 16371,  2213,  1010,  4748,  3501,  1010, 15156,
          1010, 19554,  1010, 20010,  1010,  4748,  3501,  1010,  4748,  3501,
          1010, 15156,  1010,  2112,  1010, 12034,  1010, 15156,  1010, 12034,
          1010,  4748,  2361,  1010, 20010,  1010,  4748,  3501,  1010,  4748,
          3501,  1010, 15156,  1012,  2003,  2023,  

In [414]:
for b in test_loader:
    break

/tmp/ipykernel_158/3831771474.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}


In [418]:
b['input_ids'].shape # ok now.

torch.Size([9, 512])

In [420]:
test_outputs = model(b['input_ids'].to(device), b['attention_mask'].to(device))

In [421]:
test_outputs

MaskedLMOutput(loss=None, logits=tensor([[[ -5.1645,  -5.2365,  -5.1280,  ...,  -4.6158,  -4.6302,  -3.2732],
         [ -2.3828,  -2.5515,  -2.5852,  ...,  -2.3454,  -2.1379,  -1.7407],
         [-11.5422, -11.5719, -11.7706,  ..., -10.6325,  -9.6628,  -4.9384],
         ...,
         [  0.8824,   0.6987,   0.6552,  ...,   0.7109,  -0.2909,  -0.5298],
         [ -0.4448,  -0.6146,  -0.6461,  ...,  -0.6451,  -1.4625,  -1.0038],
         [ -0.8632,  -1.0472,  -1.0868,  ...,  -1.1350,  -1.7077,  -1.5407]],

        [[ -5.2503,  -5.3134,  -5.1690,  ...,  -4.7215,  -4.7150,  -3.4021],
         [ -0.7752,  -1.0415,  -1.1343,  ...,  -0.8669,  -1.0987,  -1.0090],
         [-12.1360, -12.2667, -12.3291,  ..., -10.9412,  -9.8416,  -5.3957],
         ...,
         [  1.2465,   0.9954,   1.0162,  ...,   0.7760,  -0.0563,  -0.7392],
         [  0.0351,  -0.1904,  -0.1901,  ...,  -0.3766,  -1.0227,  -1.2554],
         [  0.1228,  -0.0961,  -0.0951,  ...,  -0.2897,  -0.7870,  -1.3773]],

        [[ 

In [423]:
test_outputs['logits'].shape

torch.Size([9, 512, 30522])

In [424]:
# get the things now

In [425]:
desired_logit = test_outputs['logits'][1][147]

In [427]:
desired_logit.shape

torch.Size([30522])

In [428]:
desired_logits = []

for idx, val in enumerate(last_indices_list):
    
    desired_logit = test_outputs['logits'][idx][val]
    desired_logits.append(desired_logit)

In [431]:
len(desired_logits)

9

In [434]:
desired_logits

[tensor([ 1.8451,  1.5967,  1.5573,  ...,  1.5875,  0.8742, -1.4997],
        device='cuda:0', grad_fn=<SelectBackward0>),
 tensor([-3.0427, -3.2585, -3.2682,  ..., -2.8442, -3.0653, -2.4101],
        device='cuda:0', grad_fn=<SelectBackward0>),
 tensor([-1.4052, -1.6459, -1.5342,  ..., -0.8876, -0.6950, -4.0745],
        device='cuda:0', grad_fn=<SelectBackward0>),
 tensor([ 1.4485,  1.1849,  1.2181,  ...,  1.1694,  0.4223, -1.2365],
        device='cuda:0', grad_fn=<SelectBackward0>),
 tensor([ 0.4256,  0.2161,  0.2306,  ...,  0.1254, -0.5941, -0.9793],
        device='cuda:0', grad_fn=<SelectBackward0>),
 tensor([-2.3563, -2.6447, -2.4691,  ..., -2.4676, -4.0849, -3.3429],
        device='cuda:0', grad_fn=<SelectBackward0>),
 tensor([ 2.0210,  1.7883,  1.8001,  ...,  1.7437,  0.8756, -1.2164],
        device='cuda:0', grad_fn=<SelectBackward0>),
 tensor([-3.7843, -3.7866, -3.5495,  ..., -4.4404, -2.3864, -1.4038],
        device='cuda:0', grad_fn=<SelectBackward0>),
 tensor([ 1.7635

In [437]:
argmax_list = []

for logit in desired_logits:
    logit_apres_argmax = torch.argmax(logit).item()
    argmax_list.append(logit_apres_argmax)

In [438]:
argmax_list

[18458, 8040, 2047, 18458, 1996, 4748, 18458, 1010, 18458]

In [439]:
tokenizer.decode(argmax_list)

'premise sc new premise the ad premise, premise'